package errmsg

const (
	SUCCESS = 200
	ERROR = 500

	//code=1000...用户模块的错误

	ERROR_USERNAME_USED=1001
	ERROR_PASSWORD_WRONG=1002
	ERROR_USER_NOT_EXIST=1003
	ERROR_TOKEN_EXIST=1004
	ERROR_TOKEN_RUNTIME=1005
	ERROR_TOKEN_WRONG=1006
	ERROR_TOKEN_TYPE_WRONG=1007

	//code=3000...分类模块的错误
	ERROR_CATENAME_USED = 2001
	ERROR_CATE_WRONG=2002
	ERROR_CATE_NOT_EXIST =2003

	//code=3000...文章模块的错误
	ERROR_ART_NOT_EXIST=3001
	ERROR_ART_WRONG=3002
)

var codeMsg = map[int]string{
	SUCCESS:"OK",
	ERROR:"FAIL",
	ERROR_USERNAME_USED:"用户名已存在～",
	ERROR_PASSWORD_WRONG:"密码错误～",
	ERROR_USER_NOT_EXIST:"用户不存在～",
	ERROR_TOKEN_EXIST:"TOKEN 不存在～",
	ERROR_TOKEN_RUNTIME:"TOKEN 已过期～",
	ERROR_TOKEN_WRONG:"TOKEN 错误~",
	ERROR_TOKEN_TYPE_WRONG:"TOKEN 格式错误～",

	ERROR_CATENAME_USED:"类别名已存在～",
	ERROR_CATE_WRONG:"类别错误～",
	ERROR_CATE_NOT_EXIST:"类别不存在～",

	ERROR_ART_NOT_EXIST:"文章不存在",
	ERROR_ART_WRONG:"文章错误",
}

//GetErrMsg 根据错误码返回对应的错误信息
func GetErrMsg(code int)string{
	return codeMsg[code]
}